### ISSUE TITLE
Define a license

### ISSUE THREAD

**Issue by haesleinhuepf** [psobolewskiPhD/napari_scripts#1]
Hi Peter @psobolewskiPhD ,

great work ongoing here! Would you mind adding a license to this repository? That would allow others to take some of your code and re-use it in their code, e.g. in similar napari-plugins. For example, if your license is compatible with the one in [napari-plot-profile](https://github.com/haesleinhuepf/napari-plot-profile/blob/main/LICENSE), we would make the best out of both profile plotters.

See also: https://choosealicense.com/

Best,
Robert

**Comment by psobolewskiPhD** [comment]
Yes, of course.
I guess a repo started from within VS Code didn't prompt me for that, which I think starting in GitHub does.
I mean I did this for personal use as a learning thing, but happy to share.
I hope I've not infringed on anything, but I know I've copy-pasta'd from image.sc, napari.zulip, and examples & docs from many repos...

**Comment by haesleinhuepf** [comment]
Awesome, thanks! Fixed in 110cdfe216559ca267e5bd7a6b12a3887327654e
